version: 2
jobs:
  build:
    environment:
      # Configure the JVM and Gradle to avoid OOM errors
      _JAVA_OPTIONS: "-Xmx3g"
    docker:
      - image: circleci/java:8-jdk
    steps:
      - checkout
      - run:
          name: build project
          command: mvn verify sonar:sonar